### ISSUE TITLE
Cannot send file.

### ISSUE THREAD

**Issue by RickyDivjakovski** [RogueException/Discord.Net#2164] opened 2022-03-03 10:01 UTC
I have ran into an issue when trying to send a file.

I have also tried the last few versions 

`[Command("map")]
        public async Task map()
        {
            var EmbedBuilder = new EmbedBuilder().WithDescription($":map: Map being distributed");
            Embed embed = EmbedBuilder.Build();
            await ReplyAsync(embed: embed);
            await Context.Channel.SendFileAsync("C:\\Users\\ricky\\Desktop\\test.txt", "Map");
        }`

returns

`The server responded with error 50035: Invalid Form Body
Inner Errors:
NUMBER_TYPE_COERCE: Value "{'Value': 0, 'IsSpecified': True}" is not long.`

Running on windows 10, .net 4.7.2

I have done quite abit of research and cannot find an issue of the sort.
Happy to upload source for examination.

**Comment by csmir** [comment] 2022-03-03 10:03
Duplicate of #2163, also please care to follow the bug report format for bug reports next time.

**Closed as completed by csmir** 2022-03-03 10:03 UTC
