### ISSUE TITLE
Discord Bot Client Ready not fired

### ISSUE THREAD

**Issue by Bari77** [RogueException/Discord.Net#1523] opened 2020-05-12 10:06 UTC
Hello,

I develop a discord bot with Discord.Net library with one other developer.
On my computer, the "Ready" event is fired, my bot correctly connect, all works, but when she try to run project (without modifications), the bot didn't connect, "Ready" event is never fired.

Can someone help us please ?

Thx a lot.

**Comment by 230Daniel** [comment] 2020-05-12 10:07
You should use the Console.Log event to debug. If your client fails to connect Ready will not be fired. Perhaps the connection is failing?

**Comment by Bari77** [comment] 2020-05-12 10:16
Our project is a Windows app with a bot inside, I can't use Console.Log to debug, but the code is pretty simple :
`public async Task StartAsync()
        {
            try
            {
                if (string.IsNullOrEmpty(Config.bot.token)) return;
                _client = new DiscordSocketClient(new DiscordSocketConfig
                {
                    LogLevel = LogSeverity.Info,
                });

                #region Client Event Handler

                _client.Ready += Global.StartGlobal;
                _client.Ready += RepeatingTimer.StartTimer;

                #endregion

                await _client.SetGameAsync("ntb!help");
                await _client.LoginAsync(TokenType.Bot, Config.bot.token);
                await _client.StartAsync();
                Global.Client = _client;
                _handler = new CommandHandler();
                await _handler.InitializeAsync(_client);
                await Task.Delay(-1);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }`
That's my principal method, when I put a break point on `Global.Client = _client;`, all pass on the two computer, but when I put a break point on `StartGlobal` or on `StartTimer` methods, that's only work on my computer.

**Comment by 230Daniel** [comment] 2020-05-12 10:20
Change your client's log level to LogSeverity.Debug and then add: `_client.Log += Client_Log;` below your _client.Ready things.

```
private async Task Client_Log(LogMessage Message)
        {
                Console.WriteLine($"[{DateTime.Now}] [{Message.Source}] {Message.Message}");
        }
```

**Comment by Bari77** [comment] 2020-05-12 10:51
![image](https://user-images.githubusercontent.com/20283367/81675549-476eea80-944f-11ea-9883-7bcd89cd1236.png)

**Comment by 230Daniel** [comment] 2020-05-12 10:54
What version of Discord.NET are you using? Ensure you're on the latest, perhaps even try the dev version. Other than that, perhaps this known issue is causing the problem on windows7/vista whichever that is? 
![image](https://user-images.githubusercontent.com/49287178/81675979-5782cc00-9447-11ea-976f-f585f6ec9bad.png)

**Comment by Bari77** [comment] 2020-05-12 11:01
Ok, the other developer works on win7 and me on 10, can be provided by it, we use, v2.2.0 of Discord.Net.
PS : We use .Net Framework 4.6.1

**Comment by Bari77** [comment] 2020-05-12 11:31
We find the solution :
`_client = new DiscordSocketClient(new DiscordSocketConfig
                {
                    LogLevel = LogSeverity.Info,
                    WebSocketProvider = WS4NetProvider.Instance
                });`
If you are using .NetFramework, add Discord.Net.Provider.WS4Net package, and add WS4NetProvider.Instance in config.
Thx for your help. Issue can be closed.

**Comment by SubZero0** [comment] 2020-05-12 17:20
@Bari77 if the issue is solved, please close it.
![image](https://user-images.githubusercontent.com/3085008/81725095-b9e5c780-945b-11ea-8cb8-a6dca015ed14.png)

**Closed as completed** 2020-05-12 22:24 UTC
