### ISSUE TITLE
Use the new base url `discord.com/api`

### ISSUE THREAD

**Issue by ArcticLampyrid** [RogueException/Discord.Net#1598] opened 2020-08-05 00:50 UTC
[In the official document](https://discord.com/developers/docs/reference#api-reference), base url has been defined as `https://discord.com/api` instead of `https://discordapp.com/api`.
And usually there are better routing rules towards `discord.com` than `discordapp.com`. (at least for my ISP)

**Comment by SubZero0** [comment] 2020-08-05 00:56
Duplicate of #1512

**Closed as completed** 2020-08-05 03:05 UTC
