### ISSUE TITLE
SelfBot doesn't connects anymore.

### ISSUE THREAD

**Issue by KrasnogorskotR** [RogueException/Discord.Net#494] opened 2017-01-21 22:57 UTC
I had previously a working SelfBot, i didn't changed the code or anything, and now it's throw an exception from `Client.ConnectAsync();`. and i already checked the Token, and the token is correct and its set to `TokenType.User`. Here the stacktrace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Discord.WebSocket.DiscordSocketClient.<>c.<SyncGuildsAsync>b__117_0(SocketGuild x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Discord.WebSocket.DiscordSocketClient.<SyncGuildsAsync>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Discord.WebSocket.DiscordSocketClient.<ProcessMessageAsync>d__114.MoveNext()```

**Comment by Still34** [comment] 2017-01-23 20:36
This occasionally happens to me as well.

**Comment by captainsalt** [comment] 2017-02-02 18:52
Also happens to me a lot as well.

**Comment by FiniteReality** [comment] 2017-02-20 20:59
Mind providing a list of guilds that you're in? I think I've figured out what's causing this but it'd be nice if I could bring it to a specific cause

**Comment by Still34** [comment] 2017-02-21 04:59
I think it has to do with a specific server not available sometimes?

**Comment by FiniteReality** [comment] 2017-02-21 11:02
No, that's not why. The code which is at fault deals specifically with
guilds which aren't entirely available.

**Comment by Auralytical** [comment] 2017-03-31 05:15
@FiniteReality did we ever figure this out?

**Comment by FiniteReality** [comment] 2017-03-31 20:41
Not from what I remember, though I definitely remember that it was something due to ConcurrentDictionary returning a null value for a given key when it shouldn't be

**Comment by KrasnogorskotR** [comment] 2017-04-24 15:27
I was into the BetterDiscord guild, that guild was causing my selfbot to not connect, i had to leave that guild, and now its just connects fine.

**Comment by FiniteReality** [comment] 2017-04-24 15:41
That makes a lot of sense, and basically confirms my theory that it occurs when guilds are not available. @RogueException Any ideas why ConcurrentDictionary would return a null value for a given key when a guild is not available?

**Comment by galenguyer** [comment] 2017-05-14 04:16
This issue should be fixed with [this commit](https://github.com/RogueException/Discord.Net/commit/4c7fad78e1ff4f6701fcce87ba4e1bc6dce1cdfe). Issue is caused by large guilds being unavailable because of having too many online users.

**Comment by FiniteReality** [comment] 2017-05-31 18:23
Closing as this appears to be fixed.

**Closed as completed by FiniteReality** 2017-05-31 18:23 UTC
Labels: bug

**Comment by RXY-R** [comment] 2019-03-07 12:40
Even My Bot Doesn't Connects Anymore.... So Discord.net.dll is completely useless Right Now.>~ ~ ~ ~

**Comment by Still34** [comment] 2019-03-07 12:41
Once again, this does not relate to the issue you are commenting on; please stop commenting on unrelated issues on random issue threads, but instead open a new issue, thank you.

**Comment by RXY-R** [comment] 2019-03-07 12:43
> Once again, this does not relate to the issue you are commenting on; please stop commenting on unrelated issues on random issue threads, but instead open a new issue, thank you.

hmm thats not what i mean

**Comment by Still34** [comment] 2019-03-07 12:47
Whatever you mean, your issue clearly does not relate to this a year and a half old issue, as you had previously commented on #342 just hours ago with a similar comment with no actual feedback and or error logs. 

If you do believe your issue is related to this particular issue (which is no longer valid, as Discord.Net 2.x and above have invalidated TokenType.User by prohibiting the use of such enum on compilation), then please provide relevant logs and or description - otherwise, open a new issue.
