### ISSUE TITLE
Random disconnects and eventual failure to reconnect

### ISSUE THREAD

**Issue by storm37000** [RogueException/Discord.Net#1364] opened 2019-08-27 20:00 UTC
```
able to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
04:05:15 Gateway     Disconnecting
04:05:15 Gateway     Disconnected
04:05:16 Gateway     Connecting
04:05:16 Gateway     Resumed previous session
04:05:16 Gateway     Connected
04:45:49 Gateway     System.Exception: WebSocket connection was closed ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
04:45:49 Gateway     Disconnecting
04:45:49 Gateway     Disconnected
04:45:50 Gateway     Connecting
04:45:50 Gateway     Connected
04:45:50 Gateway     Resumed previous session
05:05:57 Gateway     System.Exception: WebSocket connection was closed ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
05:05:57 Gateway     Disconnecting
05:05:57 Gateway     Disconnected
05:05:58 Gateway     Connecting
05:07:38 Gateway     Disconnecting
05:07:38 Gateway     Disconnected
```

**Comment by Foxite** [comment] 2019-08-28 18:14
I had the same issue this morning, I have created a dump file and saved the log file, if anyone wants to take a look at it.

**Comment by SpeedyCraftah** [comment] 2019-10-05 14:41
Same issue, can someone fix this?

**Comment by NeonPhoenix** [comment] 2019-10-30 23:16
This is similar to #960 as far as I know they are still trying to figure it out but only way around it is to restart the bot entirely. Unless someone has found a way around it.

**Comment by msx752** [comment] 2020-02-27 11:27
same issue, debug mode doesn't work keeps getting same outputs, however it works well at production there will be no issue such that. i dont know why?

**note:** it seems, discordbot can not download all users on debug mode, then it stuck on loop
```
[14:19:04 INF] Shard: 0 Ready
[14:19:04 INF] Ready
[14:19:15 INF] Disconnecting
[14:19:17 INF] Disconnected
[14:19:18 INF] Connecting
[14:19:25 WRN] Failed to resume previous session
[14:19:34 INF] Connected
[14:19:34 INF] Shard: 0 Connected with 1332 Guilds and 112565 Users
[14:19:54 INF] Ready
[14:20:10 INF] Disconnecting
[14:20:12 INF] Disconnected
[14:20:13 INF] Connecting
[14:20:18 WRN] Failed to resume previous session
[14:20:27 INF] Connected
[14:20:27 INF] Shard: 0 Connected with 1332 Guilds and 115712 Users
[14:20:49 INF] Ready
[14:20:55 INF] Disconnecting
[14:20:57 INF] Disconnected
[14:20:58 INF] Connecting
[14:21:02 WRN] Failed to resume previous session
[14:21:11 INF] Connected
[14:21:11 INF] Shard: 0 Connected with 1332 Guilds and 112218 Users
[14:21:33 INF] Ready
[14:21:49 INF] Disconnecting
[14:21:52 INF] Disconnected
[14:21:53 INF] Connecting
[14:21:57 WRN] Failed to resume previous session
[14:22:06 INF] Connected
[14:22:06 INF] Shard: 0 Connected with 1332 Guilds and 112287 Users
[14:22:27 INF] Ready
```

**Comment by RheaAyase** [comment] 2020-04-14 10:26
Should be closed as duplicate of #960

**Comment by AraHaan** [comment] 2020-06-10 12:17
I have pinpointed the issue to an ``GuildAvailable`` Handler that then blocks the gateway until it times out and is possible that it can make it timeout even with a bot client that is only in a single guild.

**Comment by SubZero0** [comment] 2020-11-07 03:02
I'll be closing this as a duplicate of #960 
If you have any issue like this one, I recommend updating to the latest nightly and if not resolved, comment in that issue,

**Closed as completed by SubZero0** 2020-11-07 03:02 UTC
