### ISSUE TITLE
AudioClient never reconnects on failed Heartbeat

### ISSUE THREAD

**Issue by trigger-segfault** [RogueException/Discord.Net#1052] opened 2018-05-04 21:41 UTC
I am currently using the Beta 2.0.0 NuGet package.

At some time during the day, a heartbeat failed while the bot was connected to a voice channel (but not playing anything). It started the `Connecting` status but `Never` finished with connected.

```
09:21:27 [Warning] Audio #49: System.Exception: Server missed last heartbeat
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNe
xt()
09:21:27 [Info] Audio #49: Disconnecting
09:21:27 [Info] Audio #49: Disconnected
09:21:28 [Info] Audio #49: Connecting
```
And a `Connected` message never showed up.

With my current setup, I store the state of the current voice channel for each guild so that the bot doesn't need to keep looking it up. Is there a better way to deal with the `AudioClient` when it starts having problems? Is there anyway to tell programmatically if it's working or not?

**Comment by RheaAyase** [comment] 2020-02-19 09:39
Duplicate of #960 ?

**Closed as completed** 2021-11-23 15:21 UTC
