### ISSUE TITLE
DownloadUsersAsync() "doesn't work"

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1679] opened 2020-11-16 00:40 UTC
This is an FYI issue for everyone with these issues.

You need MEMBERS intent for `DownloadUsersAsync()` to work. (If you ask for presences with this operation, presence intent is also required.) Enable it on your bot page: https://discord.com/developers/applications

**It Hangs**
- See [this comment](https://github.com/discord-net/Discord.Net/issues/1679#issuecomment-728382261)

**Comment by 230Daniel** [comment] 2020-11-16 00:43
Why is this required? For people with verified bots such as myself it's not a simple matter of enabling each one. I don't need to know who's online and who's not, I just need a list of users, their roles etc.

**Comment by SubZero0** [comment] 2020-11-16 01:45
> You need PRESENCES intent as well as MEMBERS for `DownloadUsersAsync()` to work.

This isn't true. You only need the server members intent to be able to download and receive users in gateway events (except GUILD_CREATE that needs the presence intent for some reason according to another dev, but this doesn't interfere with the download).
Without presence, they will all be "offline" since that's related to presences (including activities).

**Comment by xilence222** [comment] 2020-11-16 02:21
I have both intents enabled but DownloadUsersAsync doesn't finish just hangs, setting the .Wait() to 30 seconds I end up with around 30-60 users in the cache. The guild is much bigger than this.

**Comment by 230Daniel** [comment] 2020-11-16 07:54
> This isn't true. You only need the server members intent to be able to download and receive users in gateway events (except GUILD_CREATE that needs the presence intent for some reason according to another dev, but this doesn't interfere with the download).
@SubZero0 

I agree, I managed to get this working as you described on several bots with only a few servers. However, I've not had any success on my larger bot for which enabling the presence intent isn't justifiable. Last night I tried setting AlwaysDownloadUsers to true and doing nothing else, now 7 hours later there is no evidence of downloaded users.

**Edit:** Here's some more information; it looks like the DownloaderPromise tasks aren't being completed. This is about 9 hours since the bot started up with AlwaysDownloadUsers = true.

![image](https://user-images.githubusercontent.com/49287178/99232139-75136280-27e9-11eb-91bb-c2df74e5f2c9.png)

**Comment by SubZero0** [comment] 2020-11-16 09:09
The most common issue that I see in the support channel is people **not having the server member intent enabled for the correct bot** (wrong application, forgot to save, etc) so I would suggest looking again to be sure you actually enabled it.
If you don't know what intents are, I recommend reading about it in the [Discord Docs](https://discord.com/developers/docs/topics/gateway#gateway-intents), more specifically about [privileged intents](https://discord.com/developers/docs/topics/gateway#privileged-intents) that require you to toggle it in your bot application in the [dev portal](https://discord.com/developers/applications).

If that isn't your case, I highly recommend updating to the [latest nightly](https://github.com/discord-net/Discord.Net#unstable-myget) first since it has some bug fixes (example: 084db253f32269e364c7106898f2c1b34a8727ff that should handle a change made by Discord like stated on the issue linked).

Other issues that could cause this would be:
- Missing required intents when specifying them (GatewayIntents.GuildMembers and/or GatewayIntents.Guilds)
- Blocking the gateway thread (there should be a warning in the client logger), download users is a gateway request so blocking it would make it impossible to process it and complete the task.
- ~~Hitting the gateway ratelimit (120r/60s), each guild is a single request now so it's possible to easily hit it. (related to #1537 - temporary fix: manually download and add a delay to not hit the ratelimit)~~ It was merged in latest

There is probably more, but I won't remember them all.
If you went through this all and it still doesn't work, there's a few things you can still try:
- Change the log level for the client to Verbose and check what's going on (it'll log incoming/outgoing requests);
- Debug Discord.Net locally;
- Create a small repro so I can try it myself (my tests with `Discord.Net (unofficial)#5227` [docs bot] in Discord API behaved correctly when changing intents in the dev portal and client config).

**Comment by 230Daniel** [comment] 2020-11-16 09:57
I did some local debugging and found that guild members cache was being successfully downloaded for some guilds. It seems that my bot keeps getting stuck on a specific guild and never moves past it. I took a [screen recording](https://youtu.be/DNCP5V6Op4A) of the debug console, filtered only to show logs containing `guild_members_chunk` or `requestguildmembers`, which shows the guild members being downloaded successfully before stopping on 117 guilds. I left it there for a few minutes but it never downloaded more members.

To reproduce (hopefully):

* Use the latest nightly build and specify relevant intents
* Use a bot on a fair amount of servers (mine is on about 600)
* Do not specify AlwaysDownloadUsers in the DiscordSocketConfig
* In the client's Connected handler, call DiscordSocketClient.DownloadUsersAsync(), specifying all of the client's guilds
* Wait for it to stop on a specific number every time
* DownloadUsersAsync() does not return or throw an exception

**Comment by RheaAyase** [comment] 2020-11-16 13:48
> > You need PRESENCES intent as well as MEMBERS for `DownloadUsersAsync()` to work.
> 
> This isn't true. You only need the server members intent to be able to download and receive users in gateway events (except GUILD_CREATE that needs the presence intent for some reason according to another dev, but this doesn't interfere with the download).
> Without presence, they will all be "offline" since that's related to presences (including activities).

How am I supposed to interpret/explain this then?
![image](https://user-images.githubusercontent.com/13802951/99259103-d18e7600-2819-11eb-817e-22ab89717e77.png)

**Comment by RheaAyase** [comment] 2020-11-16 13:50
In other words, is that the reason why it seemingly functions that way, why so many people have a problem with it? (requesting `presences=true`?) Or ... what? Either way, I created this ticket to stop the spam in other unrelated ones.

I've edited the OP to clarify the difference maybe.

**Comment by SubZero0** [comment] 2020-11-16 20:01
> How am I supposed to interpret/explain this then?

It's talking specifically about the [`presences?` field](https://discord.com/developers/docs/topics/gateway#request-guild-members-guild-request-members-structure) that we don't even have in our [RequestMemberParams](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/API/Gateway/RequestMembersParams.cs) so it will default to false and shouldn't be the cause.

**Comment by RheaAyase** [comment] 2020-11-16 22:28
Allrighty didn't know it wasn't there at all.

**Comment by SubZero0** [comment] 2020-11-16 23:02
@230Daniel Huh, that number of requests is awfully suspicious and dangerous.
The gateway has a ratelimit of 120r/60s and you did 117 of them there (and there's still identify, heartbeat and maybe some other requests), so you might be reaching it and the gateway connection might have been dropped (plus ignoring all the following requests).

Maybe more reasons to polish and merge #1537 soon.

Could you try doing the requests manually + delaying them and see if you can succesfully download all? As doing 90 or so downloads per minute.

**Comment by 230Daniel** [comment] 2020-11-16 23:22
Ah I see, that's probably what's going on then. I can confirm that on occasion I've seen disconnects occur while the downloads are happening.

I added a foreach loop to my connected handler with a delay of 1 second between starting the download for each guild (discarding the task that it creates). I noticed some severe latency at times when this was happening, I presume that's down to so much traffic going over the network that it doesn't leave enough space for other traffic. 

For now, I think that this is the best way to go about populating the user cache for a large bot but in the future, I'll optimise to only download users for guilds which require such.

Thank you very much for your help SubZero!

![image](https://user-images.githubusercontent.com/49287178/99321247-4b981c80-2865-11eb-8ef3-7506721a70e2.png)

**Comment by SubZero0** [comment] 2020-11-17 00:14
Glad to help.

@RheaAyase would you mind linking to my comment instead since it should contain most of the causes and solutions about it? Or add that info to the first post.

**Comment by Noxxys** [comment] 2021-04-04 20:57
Hi, I'm in the same case:
- I'm developing a bot which is in only 2 servers now: one with 600+ users, and the other one just 3 (a test server)
- I've enabled both intents (PRESENCE INTENT and SERVER MEMBERS INTENT) in the Discord's developer website, saved them, and even kicked and reinvinted the bot after that
- the `DownloadUsersAsync` call hangs on the 600 user server, but it works very fast on the 3 user server
- whenever I restart the bot (locally) and try to send a command to it, I get the following warnings:

```
warn: TaggerBot.ClientBackgroundService[0]
      A MessageReceived handler is blocking the gateway task.
warn: TaggerBot.ClientBackgroundService[0]
      [null]
      Discord.WebSocket.GatewayReconnectException: Server missed last heartbeat
         at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
info: TaggerBot.ClientBackgroundService[0]
      Disconnecting
```

Are there any settings I need to enable on the application's side to make it work? And if so, how?

**Comment by quinchs** [comment] 2022-02-03 19:29
With Discord.Net >3.0 you need to specify the intent in your clients config, its also best practice to not download users on the gateway thread incase the call lasts long.

**Closed as completed by quinchs** 2022-02-03 19:29 UTC
