### ISSUE TITLE
High amount of rate limits cause CPU usage to be maxed out.

### ISSUE THREAD

**Issue by KrykiZZ** [RogueException/Discord.Net#1440] opened 2020-01-19 18:05 UTC
To reproduce: run the bot then spam a single command. After some time your CPU usage maxes out.

Tested on multiple computers with different cpu's

**Comment by k-boyle** [comment] 2020-01-19 18:07
This is a duplicate of https://github.com/discord-net/Discord.Net/issues/1439

**Closed as completed** 2020-01-19 18:28 UTC
