### ISSUE TITLE
Some issues with TypeReaders

### ISSUE THREAD

**Issue by aequasi** [RogueException/Discord.Net#229] opened 2016-08-26 21:24 UTC
1) Using the ChannelTypeReader wont work on the #general channel (eg: `!test general` or `!test #general`)
2) Using ChannelTypeReader wont work on channel mentions (eg: `!test #some-channel`)
3) MessageTypeReader doesn't seem to work when using an id (eg: `!test <channel_id>`)
4) RoleTypeReader throws an exception

```
Exception Thrown: Object of type 'System.Collections.Generic.Dictionary`2[System.UInt64,Discord.Commands.TypeReaderValue]' cannot be converted to type 'Discord.IRole'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Discord.Commands.Command.<>c__DisplayClass38_0.<BuildAction>b__0(IMessage msg, IReadOnlyList`1 args)
   at Discord.Commands.Command.<Execute>d__35.MoveNext()
[Gateway] Error handling Dispatch (MESSAGE_CREATE): Object of type 'System.Collections.Generic.Dictionary`2[System.UInt64,Discord.Commands.TypeReaderValue]' cannot be converted to type 'Discord.IRole'.
```

**Comment by Kwoth** [comment] 2016-08-27 00:49
Confirming that this happens on role type readers.

**Comment by RogueException** [comment] 2016-08-27 05:29
Which version is this? TypeReaders recently got an overhaul.

**Comment by aequasi** [comment] 2016-08-27 06:23
latest

**Comment by RogueException** [comment] 2016-08-27 11:22
1 and 2 fixed by https://github.com/RogueException/Discord.Net/commit/f2c38567b62207794a7bd806cc5e421e4d31cdab
3 is currently by design, it will only work if that message is in cache. This one's up for discussion.
4 was fixed by https://github.com/RogueException/Discord.Net/pull/231

**Comment by khionu** [comment] 2016-08-27 13:26
I think it should be able to call the API for the message. I don't see the need for it to be limited like that.

**Comment by RogueException** [comment] 2016-08-27 13:30
I'm wary of internal things that people can abuse to force rate limits to be hit

**Comment by khionu** [comment] 2016-08-27 14:00
Which is why I like the idea of adding a bunch of Typereaders, with constructors that take some configs, that aren't preinstalled into the Command Service

**Comment by RogueException** [comment] 2016-08-27 22:20
Something like that, I think should just be configured at the service level in a single place.

**Comment by khionu** [comment] 2016-08-28 14:26
Not an attribute, and I don't think there's enough we could put into a CommandServiceConfig object..... :/

**Closed** 2016-08-28 20:28 UTC
Labels: commands, discussion

**Comment by RogueException** [comment] 2016-08-28 20:33
(Moved discussion to #243)
