### ISSUE TITLE
Discord bot not going offline when disconnecting

### ISSUE THREAD

**Issue by pogrammerx** [RogueException/Discord.Net#2569] opened 2023-01-17 21:40 UTC
This is not intended behaviour, if i run client.LogOutAsync() and client.StopAsync() then the bot stays online for a few minutes,
and i cant set the status to Offline / Invisible for some reason.

**Comment by cjbonn** [comment] 2023-01-20 11:32
This is just standard behavior for almost all applications. It takes a moment for the clients to reflect that a user is no longer online.

**Comment by Quahu** [comment] 2023-01-20 11:44
> This is just standard behavior for almost all applications. It takes a moment for the clients to reflect that a user is no longer online.

This statement is incorrect; closing the Discord gateway connection properly will cause the bot's status to immediately transition to offline. Any issues with the bot remaining online would be due to library or user error.

**Comment by cjbonn** [comment] 2023-01-20 11:58
> > This is just standard behavior for almost all applications. It takes a moment for the clients to reflect that a user is no longer online.
> 
> This statement is incorrect; closing the Discord gateway connection properly will cause the bot's status to immediately transition to offline. Any issues with the bot remaining online would be due to library or user error.

Go offline on an account and watch from an alt, then tell me again that it's immediate. App clients (not exclusive to discord) will only immediately reflect someone logging out immediately if the status update itself is portrayed to the client, otherwise most apps fall back on a timeout system or periodically pinging a source of truth. Either way, it's not instant. I imagine his perception is from his client, which would make my statement factual. Status updates (ie going invisible) _is_ immediate, as would make sense with the presence intents. Logging off, however, is not.

**Comment by Quahu** [comment] 2023-01-20 12:23
> Go offline on an account and watch from an alt, then tell me again that it's immediate.

![offline](https://user-images.githubusercontent.com/24848652/213693214-4821f3c9-8cca-4bd5-bec8-0937e9af82e7.gif)

I'm telling you again that it's immediate. I'm not updating the status, just simply closing the connection.

**Comment by cjbonn** [comment] 2023-01-20 13:02
I had tested on my end as well to sanity check myself since I've noticed this behavior for 2+ years and it took 2 minutes to reflect the offline state in my discord client. Same behavior occurred with a user logout. ¯\_(ツ)_/¯ sounds like its an inconsistency within discord or its clients then, don't know what to tell ya. Client heartbeat maybe ?

**Comment by CollinHerber** [comment] 2023-01-20 14:14
@cjbonn Not telling any lies. I've experienced and tested this myself.
The majority of the time it takes 1-2 minutes for the bot to go offline, regardless if you're using Discord.NET or not.

**Comment by pogrammerx** [comment] 2023-01-20 14:41
Why does setting the status to anything but offline, work immediantly?

**Comment by cjbonn** [comment] 2023-01-20 22:36
> Why does setting the status to anything but offline, work immediantly?

Updating status is a [gateway event](https://discord.com/developers/docs/topics/gateway-events#presence-update)

**Comment by kantraksel** [comment] 2023-01-26 12:28
[Gateway#Initiating a Disconnect](https://discord.com/developers/docs/topics/gateway#initiating-a-disconnect)

> When you close the connection to the gateway with close code 1000 or 1001, your session will be invalidated and your bot will appear offline.
> If you simply close the TCP connection or use a different close code, the session will remain active and timeout after a few minutes.

**Comment by csmir** [comment] 2023-02-09 16:44
I cannot reproduce this issue, the same behavior is seen in this library as with Quahu's included example. Closing until further followup if necessary.

**Closed as completed by csmir** 2023-02-09 16:44 UTC
