### ISSUE TITLE
[Bug]: SocketTextChannel.GetMessagesAsync sometimes returns Messages with missing attachments

### ISSUE THREAD

**Issue by cobrafast** [RogueException/Discord.Net#2492] opened 2022-10-18 16:12 UTC
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

Consider the following example code, executed on a "media" channel, i.e. every message has an image or video attached.

```c#
var channel = _DiscordSocketClient.GetGuild(guildId).GetTextChannel(channelId);
int messages = 0, attachments = 0;
foreach (var message in await channel.GetMessagesAsync(someOlderMessageId, Direction.After, 256).FlattenAsync())
{
	messages++;
	attachments += message.Attachments.Count;
}
if (messages > 0)
	Debug.Assert(attachments > 0);
```

Now, about a third of the time this code is executed the assertion fails, no attachments were returned when actually there are.
The amount of messages since `someOlderMessageId` is usually no more than a dozen in the actual scenario.

As per the Docs I see no mention of this problem or how to detect incomplete messages.

My `GatewayIntents` are `GatewayIntents.AllUnprivileged | GatewayIntents.GuildMembers | GatewayIntents.MessageContent`.

Am I doing something wrong?

### Version

3.8.1

### Logs

(none)

### Packages

Discord.Addons.Hosting 5.1.0

**Comment by Misha-133** [comment] 2023-07-05 23:08
Sorry for a late response.

Can you still reproduce the issue on DNet v3.11.0?

**Comment by Mailaender** [comment] 2023-09-24 08:21
I have the same problem with empty `message.Attachments` on 3.11.0 and 3.12.0.

**Comment by Misha-133** [comment] 2023-12-04 22:18
Closing due to lack of followup.

**Closed as completed by Misha-133** 2023-12-04 22:18 UTC
Labels: bug
