### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException: "Unknown permission target."

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1594] opened 2020-07-31 22:05 UTC
```
Newtonsoft.Json.JsonSerializationException: "Unknown permission target."

   at Discord.Net.Converters.PermissionTargetConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
<snip five billion lines>
   at Discord.API.DiscordRestApiClient.GetAuditLogsAsync(UInt64 guildId, GetAuditLogsParams args, RequestOptions options)
```

I've not investigated closer yet.

**Comment by RheaAyase** [comment] 2020-07-31 22:11
```
System.InvalidCastException: "Unable to cast object of type 'System.Int64' to type 'System.String'."

   at Discord.Net.Converters.PermissionTargetConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
<snip five billion lines>
   at Discord.Rest.ChannelDeleteAuditLogData.Create(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
   at Discord.Rest.AuditLogHelper.CreateData(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
   at Discord.Rest.RestAuditLogEntry..ctor(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model, IUser user)
   at Discord.Rest.RestAuditLogEntry.Create(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model)
```

**Comment by RheaAyase** [comment] 2020-07-31 22:13
This is a "new" error. I'm not sure if Discord changed something or what's up again...

**Comment by FiniteReality** [comment] 2020-08-01 01:02
Probably because Discord changed their permissions entries in audit logs yet again.

**Comment by SubZero0** [comment] 2020-08-01 06:30
It seems they are sending the overwrite type with integers.
![image](https://user-images.githubusercontent.com/3085008/89095696-c157a580-d3a6-11ea-8792-d5585bc2e9bd.png)
This is an audit log of a channel deletion with a single role overwrite.
While the [discord api docs for the overwrite structure](https://discord.com/developers/docs/resources/channel#overwrite-object-overwrite-structure) states it's either "member" or "role", it actually sent `0` for "role" and `1` for "member".

**Comment by SubZero0** [comment] 2020-08-01 07:10
Just confirming it's actually an issue with Discord and it should be fixed, so we don't need to change anything.

![image](https://user-images.githubusercontent.com/3085008/89096405-e3ecbd00-d3ac-11ea-897a-16bca0bf20a1.png)

**Comment by RheaAyase** [comment] 2020-10-28 12:25
@SubZero0 Hi, any idea if this was resolved? Got different issues with audit logs now so I wonder if they fixed it by breaking something else.

```
Object reference not set to an instance of an object.
    at Discord.Rest.RestUser.Create(BaseDiscordClient discord, IGuild guild, User model, Nullable`1 webhookId)
    at Discord.Rest.RestUser.Create(BaseDiscordClient discord, User model)
    at Discord.Rest.MessageUnpinAuditLogData.Create(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
    at Discord.Rest.AuditLogHelper.CreateData(BaseDiscordClient discord, AuditLog log, AuditLogEntry entry)
    at Discord.Rest.RestAuditLogEntry..ctor(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model, IUser user)
    at Discord.Rest.RestAuditLogEntry.Create(BaseDiscordClient discord, AuditLog fullLog, AuditLogEntry model)
    at Discord.Rest.GuildHelper.<>c__DisplayClass28_1.<GetAuditLogsAsync>b__2(AuditLogEntry x)
    at System.Linq.Enumerable.SelectArrayIterator`2.ToArray() in /_/src/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 83
    at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items) in /_/src/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableArray.cs:line 112
    at Discord.Rest.GuildHelper.<>c__DisplayClass28_0.<<GetAuditLogsAsync>b__0>d.MoveNext()
```

**Comment by SubZero0** [comment] 2020-10-28 14:39
@RheaAyase I would hope so but didn't check myself. That looks like they didn't send the User, the question now is if it is an issue with Discord or working as intended (because afaik you can only pin/unpin user messages so there should be one).

**Comment by SubZero0** [comment] 2020-11-17 18:25
I'll be closing this since the main issue was resolved, it was an issue with what Discord sent and should be fixed.

**Closed as completed by SubZero0** 2020-11-17 18:25 UTC
