### ISSUE TITLE
CurrentUser with ICommandContext on ShardedClient is broken

### ISSUE THREAD

**Issue by BlackOfWorld** [RogueException/Discord.Net#1910] opened 2021-08-16 18:57 UTC
I asked this on Discord server and we found out some things.

Test source code:
```
public class Test : ModuleBase<ICommandContext>
{
        [Command("test", RunMode = RunMode.Async)]
        [Remarks("test <userid/mention> [userid/mention]")]
        [Summary("test")]
        public async Task Test(IUser user, IUser user2 = null)
        {
          if (user2 == null) user2 = Context.Client.CurrentUser;
        }
}
```

As you can see, it will throw a NullReferenceException when the if statement is executed. What is more weird is that, when hovering over Context.Client, VS tells us there are 2 CurrentUsers! One is null and one is properly set. ![Screenshot](https://user-images.githubusercontent.com/16164933/129615256-c6eab676-7466-4bcc-92e6-72cf7cbfad0c.png)
I'm not sure what causes this, but my gut tells me it might be something to do with https://github.com/discord-net/Discord.Net/blob/1b64d19c845cb7c612a1c52288c8b44cff605105/src/Discord.Net.WebSocket/Commands/ShardedCommandContext.cs#L9

If ICommandContext was replaced with ShardedCommandContext, everything will start working again and CurrentUser is no longer null.

**Comment by quinchs** [comment] 2021-11-24 17:19
I don't know if this might be related to https://github.com/discord-net/Discord.Net/pull/1864 or not, are you using 2.4.0?

**Comment by BlackOfWorld** [comment] 2021-11-24 18:50
When this issue was created, I was using Discord.Net v3.
Now I'm using Discord.Net Labs and it's still present.

**Comment by quinchs** [comment] 2021-11-24 18:52
@Cenngo Can you take a look at this? you might have insights I don't.

**Comment by Cenngo** [comment] 2021-11-24 21:05
So here is my initial assumption:
`BaseSocketClient`s `CurrentUser` property hides the `CurrentUser` property that is exposed by `IDiscordClient`. Although the `BaseSocketClient` creates an assigns a `SelfUser` to its own `CurrentUser` property this assignment process isn't carried down the inheritance chain. Since `ICommandContext` exposes the `IDiscordClient`, `CurrentUser` property of the `Context.Client` is never assinged.

We need to do some further investigation but this feels really similar to the issue i fixed in Discord-Net-Labs/Discord.Net-Labs#100

**Comment by BlackOfWorld** [comment] 2021-11-24 22:15
My Discord.Net Labs version is 3.3.0

**Comment by Cenngo** [comment] 2021-11-24 22:32
@BlackOfWorld can you run the same test by adding this:
```csharp
/// <inheritdoc />
        ISelfUser IDiscordClient.CurrentUser => CurrentUser;
```
to `DiscordShardedClient`:Line501

**Comment by Cenngo** [comment] 2021-11-24 23:43
it is [this line](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordShardedClient.cs#L61) that is causing the unintended behaviour. Since this property doesnt implement a setter, BaseDiscordClient.CurrentUser is never assigned but BaseSocketClient.CurrentUser is still accessible because this property overrides the virtual property of the BaseSocketClient. I will try to come up with a solution for this.

**Comment by quinchs** [comment] 2021-11-24 23:46
> it is [this line](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordShardedClient.cs#L61) that is causing the unintended behaviour. Since this property doesnt implement a setter, BaseDiscordClient.CurrentUser is never assigned but BaseSocketClient.CurrentUser is still accessible because this property overrides the virtual property of the BaseSocketClient. I will try to come up with a solution for this.

Please open a PR here instead of labs when you've got the fix

**Comment by Cenngo** [comment] 2021-11-25 00:17
> > it is [this line](https://github.com/discord-net/Discord.Net/blob/dev/src/Discord.Net.WebSocket/DiscordShardedClient.cs#L61) that is causing the unintended behaviour. Since this property doesnt implement a setter, BaseDiscordClient.CurrentUser is never assigned but BaseSocketClient.CurrentUser is still accessible because this property overrides the virtual property of the BaseSocketClient. I will try to come up with a solution for this.
> 
> Please open a PR here instead of labs when you've got the fix

Alright. I found a way to fix this but its very far from ideal. I'll take a deeper look at this tomorrow.

**Closed as completed** 2021-11-25 15:22 UTC
Labels: Needs investigation
