### ISSUE TITLE
[Bug]: 400 Bad Request on Bot Start.

### ISSUE THREAD

**Issue by SecondNewtonLaw** [RogueException/Discord.Net#2656] opened 2023-04-04 20:06 UTC
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When I attempt to run the Discord bot in a Linux machine to host it, the connection fails to be stablished with error 400 (Bad Request), I have other Discord bots running in the same machine, the Token is correct, and when I execute it in my Windows machine the bot works as expected, but it does not in a Linux server.

### Version

3.10.0

### Logs

```log
[Discord.Net Log] 19:56:41 Discord     Discord.Net v3.10.0 (API v10)
[Init/INFO] Starting Up...
[Discord.Net Log] 19:56:41 Gateway     Connecting
[Discord.Net Log] 19:56:41 Gateway     Connecting ApiClient
[Discord.Net Log] 19:56:41 Gateway     Discord.Net.HttpException: The server responded with error 400: BadRequest
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetBotGatewayAsync(RequestOptions options)
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync()
   at Discord.API.DiscordSocketApiClient.ConnectAsync()
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync()
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken)
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
[Discord.Net Log] 19:56:41 Gateway     Disconnecting
[Discord.Net Log] 19:56:41 Gateway     Disconnecting ApiClient
[Discord.Net Log] 19:56:41 Gateway     Waiting for heartbeater
[Discord.Net Log] 19:56:41 Gateway     Waiting for guild downloader
[Discord.Net Log] 19:56:41 Gateway     Clearing large guild queue
[Discord.Net Log] 19:56:41 Gateway     Raising virtual GuildUnavailables
```

### Packages

**Masked.Library 1.4.5** (Custom library just to make working with Slash Commands on Discord.Net a bit easier and more straight forward with some other stuff I use sometimes, the other bot uses it, so I don't think it's the cause), **Newtonsoft.Json 13.0.2**, **Spectre.Console 0.45.0** (AnsiConsole).

**Comment by markski1** [comment] 2023-04-23 20:01
This doesn't seem caused by Discord.NET library.

Still, I would suggest you ensure everything regarding the bot's configuration and how it presents itself to Discord is valid. BadRequest errors usually show up when, well, a value in a request is "bad". Maybe a value is too long, or too short, or empty when it shouldn't be, or something like that. Especially since you mention running other bots (which I assume are also on DNET) just fine.

If you're reading a value (such as the bot's token) out of a file, make sure there's no linebreaks. This type of stuff tends to get automatically trimmed in Windows, but might get included in the value (and therefore in the request) on Linux, in my experience.

**Comment by Misha-133** [comment] 2023-08-11 22:15
Closing due to lack of followup

**Closed as completed by Misha-133** 2023-08-11 22:15 UTC
Labels: bug
