### ISSUE TITLE
[Feature Request] Webhook Delete, Edit And Create Handlers (Or Similar)

### ISSUE THREAD

**Issue by MistressPlague** [RogueException/Discord.Net#1785] opened 2021-02-27 19:36 UTC
Please?

**Comment by MistressPlague** [comment] 2021-04-22 11:57
I did not mean webhook messages, I mean the webhooks themselves.

**Comment by SubZero0** [comment] 2021-04-22 14:15
If you meant WEBHOOK_UPDATE, there was a suggestion about it, #1450 
Or did you mean INTEGRATION_x events?

**Comment by MistressPlague** [comment] 2021-04-22 14:28
The creation of a webhook, editing of one (such as name change) or most
importantly a webhook being deleted.

**Comment by SubZero0** [comment] 2021-04-22 14:44
After some testing, webhooks will only fire a WEBHOOKS_UPDATE when any of those events happen (even when it's inside the integrations tab).
So I'll be closing this issue as a duplicate of #1450 , any updates will be done there.

**Closed as completed by SubZero0** 2021-04-22 14:44 UTC

**Comment by MistressPlague** [comment] 2021-04-22 14:52
Discord is dumb ig :/
