### ISSUE TITLE
Downloading messages while the cache is empty results in empty "list."

### ISSUE THREAD

**Issue by RheaAyase** [RogueException/Discord.Net#1517] opened 2020-05-07 16:42 UTC
If you download messages while there are some in the cache, everything is fine. If the cache is (enabled and) empty, then it returns IAsyncEnumerable of collections (a book of pages) where the ~~first collection (page)~~ __everything__ is empty. (This screws up standard await-foreach consumption, ~~while it doesn't matter for~~ `flatten`ing __as well__.)

Hacky workaround on the user side is to disable cache.

**Comment by RheaAyase** [comment] 2020-05-12 09:33
It would seem that I was wrong in that assumption that the other non-empty pages were there. They're not. It's absolutely empty. Failure to download anything what so ever, so even flatten won't work. Edited OP to reflect this.

**Comment by SubZero0** [comment] 2020-06-18 20:57
Just a small update, since #1526 was merged, the cache won't add an empty first page if there's no results anymore. Besides that, it's like I said before on discord, I couldn't reproduce any other empty page.

**Closed as completed** 2021-11-24 17:20 UTC
Labels: bug, to investigate
