### ISSUE TITLE
Bot disconnected from voice channel with "4008: rate limited" error

### ISSUE THREAD

**Issue by JOBBIN9422** [RogueException/Discord.Net#1665] opened 2020-11-03 21:15 UTC
I have a music bot which streams songs from a queue via ffmpeg (using [this example](https://discord.foxbot.me/docs/guides/voice/sending-voice.html) as a basis). 
Recently (within the last week), the bot has been frequently getting disconnected from the voice channel with a `4008: rate limited` error from the API. Usually, the following steps happen leading up to the error: 

1. User adds songs to the queue. The first song plays to completion over voice chat normally.
2. The second song is dequeued and audio plays for a few seconds before the bot is disconnected from voice with the above error. 

I am currently using the nightly Discort.NET builds, but tried rolling back to `2.2.0` after getting the error. The error still persists on `2.2.0`.

Please let me know if you need more details!

EDIT: error message
![image](https://user-images.githubusercontent.com/32369412/98042073-8a02f580-1de8-11eb-8db4-65072f4830d1.png)

**Comment by SubZero0** [comment] 2020-11-07 02:54
This is actually a duplicate of #1274 so I'll be closing this one in favor of that one. It should be fixed by #1667 anyways.

**Closed as completed by SubZero0** 2020-11-07 02:54 UTC
