### ISSUE TITLE
[Bug]: SendFileAsync(), has error: NUMBER_TYPE_COERCE: Value "{'Value': 0, 'IsSpecified': True}" is not long.

### ISSUE THREAD

**Issue by truong2307** [RogueException/Discord.Net#2170] opened 2022-03-05 14:25 UTC
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

When I use SendFileAsync(), it has error: NUMBER_TYPE_COERCE: Value "{'Value': 0, 'IsSpecified': True}" is not long.

### Version

3.4.0

### Working Version

3.2.0

### Logs

Error: Exception: The server responded with error 50035: Invalid Form Body
Inner Errors:
NUMBER_TYPE_COERCE: Value "{'Value': 0, 'IsSpecified': True}" is not long.

### Sample

```cs
[Command("ping")]
        public async Task PingAsync()
        {
            await Context.Channel.SendFileAsync("D:\\image.jpg");
        }
```

### Packages

Discord.Net.Websocket V3.4.0

**Comment by csmir** [comment] 2022-03-05 15:09
Fix is already implemented. Duplicate of #2163 & #2164. You can implement this fix by using the MyGet feed or waiting for the next update. Should be out this weekend

**Closed as completed by csmir** 2022-03-05 15:09 UTC
Labels: bug
