### ISSUE TITLE
Bot won't remain online on it's own for long. More robust reconnect mechanism needed?

### ISSUE THREAD

**Issue by Xeevis** [RogueException/Discord.Net#130] opened 2016-07-18 09:49 UTC
I've been trying to run 1.0.0-dev bot on a linux box server. I usually wake up and see bot went down and didn't manage to reconnect and gave up. I've observed several errors pertaining to this issue:

```
2016-07-18 09:28:19	stdout	[Warning] Gateway -> Server missed last heartbeat
2016-07-18 09:28:19	stdout	[Info] Gateway -> Disconnecting
2016-07-18 09:28:20	stdout	[Warning] Gateway -> Connection Closed: The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state.
```

```
2016-07-16 01:16:25	stdout	[Warning] Gateway -> Connection Closed: The server sent close 1001: "CloudFlare WebSocket proxy restarting"
2016-07-16 01:16:25	stdout	[Info] Gateway -> Disconnecting
2016-07-16 01:16:25	stdout	[Info] Gateway -> Disconnected
2016-07-16 01:16:26	stdout	[Info] Gateway -> Connecting
2016-07-16 01:16:27	stdout	[Warning] Gateway -> Connection Closed: The server sent close 4003: "Not authenticated."
```
Is there a simple way to loop reconnect at an interval so bot is back up moment it's technically possible to do so?

**Comment by RogueException** [comment] 2016-07-18 13:48
I've been able to reproduce this problem myself but I'm not sure what the issue is yet.

There's no workaround right now, it's deadlocking itself during the automatic reconnect. I'll update this issue when I know more.

**Comment by DigiTechs** [comment] 2016-07-18 16:50
Are you doing any long operations in response to, say, chat? Hooking into MessageReceived basically requires you to start a new task to ensure it doesn't block the entire client. 

I've had almost no issues on my linux machine (other than occasional network blips, but that's mostly on my side since I'm hosting it on my own hardware) after modifying my MessageReceived code to look something like this:

```csharp
private static Task MessageReceived(IMessage message)
{
	Task.Run(async () =>
	{
		await HandleCommand(message);
	});

	return Task.FromResult(0);
}
```

**Comment by RogueException** [comment] 2016-07-18 17:29
I just pushed a fix to dev for *one* deadlock issue - specifically deadlocking if an exception occurred before READY completes, but it seems unrelated. Might want to check it out just in case.

**Comment by RogueException** [comment] 2016-07-20 21:16
I pushed another deadlock fix to dev today, try it out and let me know if there's any improvement

**Comment by RogueException** [comment] 2016-07-22 08:06
I've been unable to repro this after the latest set of reconnect commits. If it happens again, feel free to reopen.

**Closed by RogueException** 2016-07-22 08:06 UTC
Labels: bug, websocket

**Comment by EwanNoble** [comment] 2017-04-19 22:43
```
Warning
System.Exception: WebSocket connection was closed ---> Discord.Net.WebSocketClosedException: The server sent close 1001: "CloudFlare WebSocket proxy restarting"
   at Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__32.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.ConnectionManager.<>c__DisplayClass28_0.<<StartAsync>b__0>d.MoveNext()
```
Had this issue occur twice today, this Issue is the only mention of the error message that I can find. Running version 1.0.0-rc, will continue to monitor.
