### ISSUE TITLE
Module preconditions don't inherit

### ISSUE THREAD

**Issue by Auxes** [RogueException/Discord.Net#269] opened 2016-09-05 19:14 UTC
Module properties don't pass to their submodules. You have to re-specify a context for every submodule in the module.

Here's a quick working example.
```cs
[Module, Name("Example")]
[RequireContext(ContextType.Guild)]
public class ExampleGroup
{
    [Command("example")]
    [Description("This command requires a guild context, and will not work in a PM.")]
    public async Task Example(IUserMessage msg)
    {
        var guild = (msg.Channel as ITextChannel).Guild;
        await msg.Channel.SendMessageAsync(guild.Name);
    }

    [Module("example"), Name("Example")]
    public class SubCommands
    {
        [Command("subcommand")]
        [Description("This one does not, and will work in a PM.")]
        public async Task Subcommand(IUserMessage msg)
        {
            var guild = (msg.Channel as ITextChannel).Guild;
            await msg.Channel.SendMessageAsync(guild.Name);
        }
    }
}

**Comment by FiniteReality** [comment] 2016-09-05 19:15
Duplicate of #263

**Comment by khionu** [comment] 2016-09-05 19:15
What Finite said

**Closed by khionu** 2016-09-05 19:15 UTC
