### ISSUE TITLE
[Bug]: Forum managing problems

### ISSUE THREAD

**Issue by FemLolStudio** [RogueException/Discord.Net#2718] opened 2023-07-04 10:34 UTC
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [X] I verified the issue was caused by Discord.Net.

### Check your intents

- [X] I double checked that I have the required intents.

### Description

I found some problem about the forum channels.

- If I trying to make more post for a forum channel DC limiting is applied, discord.net not managing it.

- When I trying to add a new Discord tag I can't keep the current tags. Im trying to use the IForumChannel.ModifyAsync method, but It waiting ForumTagProperties. By default it doesn't contain the tags. If it try to make the ForumTag to ForumTagProperties it always lose the ID (ForumTag..ToForumTagBuilder().Build();), so it rewrite the all tags in this case and the previous post losing the tags.

- IForumChannel.CreatePostWithFileAsync() - the given tags not applied for the post, I need to use the IThreadChannel.ModifyAsync() command to add a tag/tags. Idk its happening with the other 2 post creating method.

### Version

3.11.0 (latest)

### Logs

-none-

### Sample

```C#
private async Task Test(IForumChannel channel, string filePath, int tests = 1000)
        {
            for (int i = 0; i < tests; i++)
            {
                await Work(channel, filePath);
                //PROBLEM: limiting bc discord.net can't manage rightly.
                //DC Limit about every post a little and a bigger every 50 post, so idk what is the best delay
                await Task.Delay(60 * 1000);
            }
        }
        private async Task Work(IForumChannel channel, string filePath)
        {
            string[] categories = new[] { "test1", "test2", "test3", "test4", "test5", "test6" };
            string category = categories[Random.Shared.Next(categories.Length)];

            Stream stream = File.OpenRead(filePath);

            ForumTag tag = channel.Tags.FirstOrDefault(x => string.Compare(x.Name, category) == 0);

            if (tag.Id == 0)
            {
                Console.WriteLine("NEW TAG");
                await channel.ModifyAsync(x =>
                {
                    Console.WriteLine("Tags specified in ModifyAsync:" + x.Tags.IsSpecified);
                    List<ForumTagProperties> tags = new();
                    ForumTagBuilder tagBuilder = new() { Name = category };
                    tags.Add(tagBuilder.Build());
                    //PROBLEM: cant convert
                    //tags.AddRange(channel.Tags.Select(x => (ForumChannelProperties)x));

                    //PROBLEM: can't add an extra and keep the current tags in the same time, no solution yet
                    foreach (var tag in channel.Tags)
                        tags.Add(tag.ToForumTagBuilder().Build());
                    x.Tags = tags;
                });
                tag = channel.Tags.FirstOrDefault(x => string.Compare(x.Name, category) == 0);
            }

           
            IThreadChannel post = await channel.CreatePostWithFileAsync(
                category + ' ' + Random.Shared.Next(1000), 
                stream, 
                Path.GetFileName(filePath), 
                text: "Test", 
                tags: new ForumTag[] { tag });  //its not adding the tag

            //PROBLEM: need this, bc TAG NOT applied somewhy in the previous command
            await post.ModifyAsync(x => x.AppliedTags = new ulong[] { tag.Id });
        }
```

### Packages

.NET 7

**Comment by FemLolStudio** [comment] 2023-07-04 11:05
An +1 problem. When I try to run `await channel.ModifyAsync(x => x.Tags = properties);` where properties contains more than 5 element (for example 6) I get the next message:

```
System.ArgumentException: Forum channel can have max 20 tags. (Parameter 'Tags')
   at Discord.Preconditions.AtMost(Int32 obj, Int32 value, String name, String msg)
   at Discord.Rest.ForumHelper.ModifyAsync(IForumChannel channel, BaseDiscordClient client, Action`1 func, RequestOptions options)
   ```

**Comment by Misha-133** [comment] 2023-07-04 11:13
1. 
> IForumChannel.CreatePostWithFileAsync() - the given tags not applied for the post, I need to use the IThreadChannel.ModifyAsync() command to add a tag/tags. Idk its happening with the other 2 post creating method.
- yeah, seems like a bug; will be fixed shortly.


2. 
> If it try to make the ForumTag to ForumTagProperties it always lose the ID
- also is one; will be fixed soon.


3. 
> //PROBLEM: cant convert
 >  //tags.AddRange(channel.Tags.Select(x => (ForumChannelProperties)x));
- Not a bug. The `x` object in this case is `ForumTag`. It can't be casted to `ForumChannelProperties`, as ones only inherit `IForumTag` interface, not one another.


4. 
> If I trying to make more post for a forum channel DC limiting is applied, discord.net not managing it.
- It might be a bug, but the DNets ratelimiter is quite complex & old, so I doubt it will get fixed until v4.

5.
> An +1 problem. When I try to run await channel.ModifyAsync(x => x.Tags = properties); where properties contains more than 5 element (for example 6) I get the next message
- also a bug, fixed soon.

**Closed as completed** 2023-08-10 12:37 UTC
Labels: bug
