### ISSUE TITLE
Discord.Net 1.0 and "read-only" mode

### ISSUE THREAD

**Issue by pogarek** [RogueException/Discord.Net#468] opened 2017-01-06 23:48 UTC
HI

Because of #467 , I need to use 1.0. 
My app, which I would like to extend by getting data from Discord, create json feed for another app. 
There are channels on different discord servers, on which another (not mine) bots drops a data, that I would like to parse and put in the json.  So , basically, I need to connect such server (by invite or use previously accepted invite) , go to channel and listen for messages from bots. 

As you know, bots accounts cannot accept invites and on  https://discordapp.com/oauth2/authorize?client_id=XXX&scope=bot&permissions=0 i can only see a servers, that I can manage.

So how can I utilize Discord.NET here ?

**Comment by khionu** [comment] 2017-01-07 00:23
You cannot join a guild without being invited, via OAuth for Bot Accounts or via Invite for User Accounts. There is no other way to access a guild (ergo, its channels). This is by design, by Discord.

If this does not answer your question, I'm afraid you'll have to rephrase.

**Comment by pogarek** [comment] 2017-01-07 00:31
Getting the invite is not the problem.  But bots cannot accept it at all <= https://discordapp.com/developers/docs/topics/oauth2 : 

> Bots cannot utilize the friends list feature.
> Bots cannot accept invites.
> Bots are not limited to a maximum of 100 guilds.
> Bots have a per-channel and a global rate limit.

Only User Accounts can.
However I haven't found a way how to use User Accounts in 1.0.

**Comment by khionu** [comment] 2017-01-07 00:39
LoginAsync's first Parameter is a TokenType enum. Set it to User

**Comment by pogarek** [comment] 2017-01-07 01:02
Thanks. How can get the token for user ? Logging with bot token and Client Secrets gets 401 error when TokenType is set to User...

**Comment by khionu** [comment] 2017-01-07 01:11
Bot tokens are for Bot Accounts. You can only login as a user via a User Account.

**Comment by pogarek** [comment] 2017-01-07 01:13
So how can I get token for a user or login by Discord.Net with user's login/password ?

Edit : thanks to the bot in discord I was told , that user token can be found Developer Tools console, by typing : 

>  localStorage.token

**Comment by Auralytical** [comment] 2017-01-26 14:49
Looks like this is resolved, closing.

**Closed as completed by Auralytical** 2017-01-26 14:49 UTC
