### ISSUE TITLE
[Bug]: SendFileAsync

### ISSUE THREAD

**Issue by kolya112** [RogueException/Discord.Net#2173] opened 2022-03-07 11:15 UTC
### Check The Docs

- [X] I double checked the docs and couldn't find any useful information.

### Verify Issue Source

- [x] I verified the issue was caused by Discord.Net.

### Check your intents

- [x] I double checked that I have the required intents.

### Description

I updated library from 3.2.0 to 3.4.0 version. When I using "SendFileAsync" function, I getting error. At the same time, everything worked fine on version 3.2.0

### Version

3.4.0

### Working Version

3.2.0

### Logs

![image](https://user-images.githubusercontent.com/59023595/157020605-2e0cd617-602b-4d27-bc7a-90bdce7edb37.png)

### Packages

![image](https://user-images.githubusercontent.com/59023595/157020934-e1e44cae-5166-49c6-9e19-cb240d1e71be.png)

**Comment by csmir** [comment] 2022-03-07 11:18
Fix is already implemented. Duplicate of #2163, #2164 and #2170. You can implement this fix by using the MyGet feed or waiting for the next update.

**Closed as completed by csmir** 2022-03-07 11:18 UTC
Labels: bug
