### ISSUE TITLE
DeleteAsync 403

### ISSUE THREAD

**Issue by Devyre** [RogueException/Discord.Net#1640] opened 2020-10-02 08:41 UTC
Hey, ever since I upgraded my server to a community my bot keeps getting a 403 Error when I try to call message.DeleteAsync()

The bot definitely has permission to manage messages in both the channel and the entire server (the bot is even marked as Administrator)

Any ideas why this happens? I can iterate through messages just fine, so there shouldn't be issues with reaching the discord api.

**Comment by MarkusG** [comment] 2020-10-02 15:11
Are you violating the role hierarchy? If the target message's author has a role higher than the bots highest role, it won't be able to delete the message.

**Comment by Devyre** [comment] 2020-10-02 16:03
I’m not, the bots role is at the top and the target whose message I try to delete does not have a role

**Comment by joker-119** [comment] 2020-10-03 19:26
I'm having the same issue, it cannot delete any messages, the bot has the highest role in the server, and said role has Administrator, but it is unable to delete **any** messages.

`
Discord.Net.HttpException: The server responded with error 403: Forbidden
  at Discord.Net.Queue.RequestBucket.SendAsync (Discord.Net.Queue.RestRequest request) [0x003de] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.Net.Queue.RequestQueue.SendAsync (Discord.Net.Queue.RestRequest request) [0x00108] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.API.DiscordRestApiClient.SendInternalAsync (System.String method, System.String endpoint, Discord.Net.Queue.RestRequest request) [0x00116] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.API.DiscordRestApiClient.SendJsonAsync (System.String method, System.String endpoint, System.Object payload, System.String bucketId, Discord.Net.Queue.ClientBucketType clientBucket, Discord.RequestOptions op
tions) [0x000e8] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.API.DiscordRestApiClient.DeleteMessagesAsync (System.UInt64 channelId, Discord.API.Rest.DeleteMessagesParams args, Discord.RequestOptions options) [0x0023b] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.Rest.ChannelHelper.DeleteMessagesAsync (Discord.ITextChannel channel, Discord.Rest.BaseDiscordClient client, System.Collections.Generic.IEnumerable`1[T] messageIds, Discord.RequestOptions options) [0x00122] 
in <428374684bf1487b9a7949eebbe25e72>:0 
  at Security_Bot.Methods.Cleanup (Discord.Commands.ICommandContext context) [0x0049e] in <a308d19ad0384472be34161067695295>:0
`


The issue also appears to be affecting bans, the bot cannot ban anyone from the server, even those without roles

`Discord.Net.HttpException: The server responded with error 403: Forbidden
  at Discord.Net.Queue.RequestBucket.SendAsync (Discord.Net.Queue.RestRequest request) [0x003de] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.Net.Queue.RequestQueue.SendAsync (Discord.Net.Queue.RestRequest request) [0x00108] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.API.DiscordRestApiClient.SendInternalAsync (System.String method, System.String endpoint, Discord.Net.Queue.RestRequest request) [0x00116] in <428374684bf1487b9a7949eebbe25e72>:0 
  at Discord.API.DiscordRestApiClient.SendAsync (System.String method, System.String endpoint, System.String bucketId, Discord.Net.Queue.ClientBucketType clientBucket, Discord.RequestOptions options) [0x000cc] in <428374
684bf1487b9a7949eebbe25e72>:0 
  at Discord.API.DiscordRestApiClient.CreateGuildBanAsync (System.UInt64 guildId, System.UInt64 userId, Discord.API.Rest.CreateGuildBanParams args, Discord.RequestOptions options) [0x00290] in <428374684bf1487b9a7949eebb
e25e72>:0 
  at Discord.Rest.GuildHelper.AddBanAsync (Discord.IGuild guild, Discord.Rest.BaseDiscordClient client, System.UInt64 userId, System.Int32 pruneDays, System.String reason, Discord.RequestOptions options) [0x000ac] in <42
8374684bf1487b9a7949eebbe25e72>:0 
  at Security_Bot.BanSystem.DiscordBan (Discord.Commands.ICommandContext context, Security_Bot.Program program) [0x007d9] in <a308d19ad0384472be34161067695295>:0 
`

**Comment by joker-119** [comment] 2020-10-03 19:32
I would like to point out, I think this is caused by a change Discord made to their API, not a fault of a change made to Discord.net, because my bots using older versions of Discord.net (2.0 and 2.1.1) began seeing the issue at the same time as my bot using 2.2.0, and they haven't had any code changes or anything in several months.

**Comment by Devyre** [comment] 2020-10-03 19:35
I solved my problem.
The bot that kept getting 403 errors was created on an account that wasn't the Discord server's owner account.
I tried to create one on the actual owner account of the Discord server and suddenly it all worked again.
I'm unsure if being a bot of the owner account has anything to do with this or if it's also solved by simply creating a new bot.
Try to do either of these things and let me know how it goes.

Edit: So yes, this in fact is Discord API being weird and has nothing to do with Discord.Net.

**Comment by joker-119** [comment] 2020-10-03 20:18
Unfortunately for me that won't really be an option, can you confirm that the bot *needs* to be on the server owner's account? Because my bots are in a lot of servers and it would be unrealistic to have the owner of each have to make a bot just so that it can delete messages or ban people.

I don't even know where to report this issue to Discord directly.

**Comment by BobVul** [comment] 2020-10-03 20:52
Erm... You're all using bot accounts (via Discord developer options), not logging in to/controlling normal user accounts, right?

Message deletion works fine for me in a non-community server, where the bot has manage messages (or administrator) permission. Regardless of role hierarchy or the role of the author of the target message.

**Comment by joker-119** [comment] 2020-10-03 22:11
Yes I am, and it use to work until very recently, but my bot can't delete messages or issue bans, even though he has a role with Administrator.

**Comment by RheaAyase** [comment] 2020-10-03 23:33
IIRC you can not use bulk delete on a user account.
And it's definitely a problem with permissions on your server, not the bot, library, or API.

**Comment by Kein** [comment] 2020-10-13 09:39
> Are you violating the role hierarchy? If the target message's author has a role higher than the bots highest role, it won't be able to delete the message.

Are you sure it is true for bots, even/especially with Administrator role? I know that simple "Manage Messages" privilege on a user  is enough to delete anyone's message, even owner's. Why would bot with the same privs be different?

**Comment by SubZero0** [comment] 2020-11-07 02:28
Like said above, this isn't an issue with Discord.Net, so I'll be closing this.

**Closed as completed by SubZero0** 2020-11-07 02:28 UTC
