### ISSUE TITLE
Another disconnection issue

### ISSUE THREAD

**Issue by panthernet** [RogueException/Discord.Net#1572] opened 2020-06-19 10:20 UTC
Recent connection issues on my server is killing my app connection to Discord to the point it is not reestablishing. I've already had to relaunch the app like 5 times or so.

I'm not sure if this is a bug or by design. Is there a `solid` way to ensure that lib will keep try to connect with Discord? Should I implement some kind of wrapper to reinitialize Discord connection?

```
06/19/2020 12:10:51 [    Info]: Connecting
06/19/2020 12:12:26 [ Warning]: 
06/19/2020 12:12:26 [    Info]: Disconnecting
06/19/2020 12:12:26 [Critical]: Disconnected! 
System.TimeoutException: The operation has timed out.
   at Discord.ConnectionManager.WaitAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 176
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketClient.cs:line 249
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketClient.cs:line 261
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 144
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 72
06/19/2020 12:12:26 [    Info]: Disconnected
06/19/2020 12:12:35 [    Info]: Connecting
06/19/2020 12:12:35 [ Warning]: Failed to resume previous session
06/19/2020 12:12:36 [    Info]: Connected
06/19/2020 12:12:36 [    Info]: Ready
06/19/2020 12:12:36 [ Warning]: Rate limit triggered: guilds/415097131184160779/members/@me/nick
06/19/2020 12:27:43 [ Warning]: 
06/19/2020 12:27:44 [    Info]: Disconnecting
06/19/2020 12:27:44 [Critical]: Disconnected! 
Discord.WebSocket.GatewayReconnectException: Server missed last heartbeat
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 74
06/19/2020 12:27:44 [    Info]: Disconnected
06/19/2020 12:27:45 [    Info]: Connecting
06/19/2020 12:29:26 [    Info]: Disconnecting
06/19/2020 12:29:26 [Critical]: Disconnected! 
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\Net\DefaultRestClient.cs:line 139
   at Discord.Net.Rest.DefaultRestClient.SendAsync(String method, String endpoint, CancellationToken cancelToken, Boolean headerOnly, String reason) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\Net\DefaultRestClient.cs:line 74
   at Discord.Net.Queue.RestRequest.SendAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\Net\Queue\Requests\RestRequest.cs:line 31
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\Net\Queue\RequestQueueBucket.cs:line 62
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\Net\Queue\RequestQueue.cs:line 86
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 274
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions options) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 234
   at Discord.API.DiscordRestApiClient.GetGatewayAsync(RequestOptions options) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.Rest\DiscordRestApiClient.cs:line 294
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketApiClient.cs:line 151
   at Discord.API.DiscordSocketApiClient.ConnectInternalAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketApiClient.cs:line 163
   at Discord.API.DiscordSocketApiClient.ConnectAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketApiClient.cs:line 122
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketClient.cs:line 235
   at Discord.WebSocket.DiscordSocketClient.OnConnectingAsync() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\DiscordSocketClient.cs:line 261
   at Discord.ConnectionManager.ConnectAsync(CancellationTokenSource reconnectCancelToken) in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 144
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in D:\Projects\EVE\ThunderED\Discord.Net-dev\src\Discord.Net.WebSocket\ConnectionManager.cs:line 72System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
06/19/2020 12:29:26 [    Info]: Disconnected
```

**Comment by SubZero0** [comment] 2020-06-19 10:34
The suggested way is running your process under a daemon and adding a check to your connection, if it fails, kill the process and let the daemon restart it.

Example: https://gist.github.com/foxbot/7d81edab4e36497c643828638af289b8

**Comment by RheaAyase** [comment] 2020-06-19 10:37
Bots are services and should always run as such. You want to `Exit()` on `SocketException`s - these are essentially guaranteed to fail. Anything else should be fine and the client will reconnect/resume.

**Comment by RheaAyase** [comment] 2020-06-19 10:40
Also Duplicate of #960

**Comment by panthernet** [comment] 2020-06-19 10:45
Thanks for the tips!

**Comment by SubZero0** [comment] 2020-06-19 11:23
A difference from this issue from others is that yours has a more helpful stacktrace.
@panthernet did it deadlock after the last message or you just cut it? If it did, I suggest reposting it on the other issue since it might help a lot finding where the connection deadlock is.

**Comment by panthernet** [comment] 2020-06-19 11:29
@SubZero0 yes, it is the last message from Discord lib, no cuts

**Comment by AraHaan** [comment] 2020-07-14 09:17
@panthernet if you have not already I left a comment in #1580 that can also cause the deadlock eventually, with events.

**Closed as completed** 2021-11-23 15:29 UTC
