### ISSUE TITLE
Client hangs on client reconnect

### ISSUE THREAD

**Issue by brankin3** [RogueException/Discord.Net#1207] opened 2018-12-01 18:49 UTC
The client seems to hang occasionally when reconnecting, specifically when my connection is unstable. This happens in both of my bots, one that I haven't updated in months except for the library, and one that I update frequently. I don't know what causes it, but I have to restart my bot daily, sometimes hourly because of it. May or may not be related to #856, but cannot be certain.

![image](https://user-images.githubusercontent.com/17625734/49331754-83fe9d00-f55f-11e8-97e9-6540a374293d.png)

Notes: Bot only autosaves once an hour. So that means it's been "connecting" for over an hour.

**Comment by ComputerMaster1st** [comment] 2018-12-01 20:03
Hi There,

If you don't mind me asking this rather dumb question, what's the CPU Usage at the time?

**Comment by brankin3** [comment] 2018-12-02 03:00
I didn't think to check, but one of my bots should disconnect overnight so I'll let you know then.

**Comment by brankin3** [comment] 2018-12-02 09:24
Okay, it's hanging right now, but CPU usage (according to task manager) is usually 0-1% system-wide. Occasionally it'll jump to 10% or so. Not sure if that's what you're looking for. 

Also implemented a workaround for my other bot that calls StopAsync and then StartAsync when it remains disconnected for 30 seconds, and that bot hasn't stayed hung since... or actually the issue never popped back up because it's not logging having to do that >.>"

**Comment by brankin3** [comment] 2018-12-03 05:47
Running StopAsync then StartAsync doesn't seem to fix the issue when it occurs...
![image](https://user-images.githubusercontent.com/17625734/49355307-37f94880-f684-11e8-87a7-da5209cfcfce.png)

**Comment by brankin3** [comment] 2018-12-04 03:35
It... appears to be caused by deadlocking. The Closed event for `WS4NetClient` calls `DisconnectAsync` on `DiscordSocketApiClient` which requests the lock for the client. At the same time if Client gets called to connect/reconnect, it acquires that lock, and waits for the `WS4Socket` to let it pass. So the thread coming from `WS4NetClient` gets blocked, and the thread waiting for `WS4NetClient` gets blocked, resulting in nothing done, and a locked up program.

I'm not sure if this affects `DefaultWebSocketClient` or not

Edit: The `Opened` Event for the `WS4Socket` appears to wait for a websocket handshake command before firing the event, so if the connection goes through, but closes before going through the Websocket Handshake, the application deadlocks

**Comment by RheaAyase** [comment] 2020-06-19 10:39
Duplicate of #960

**Comment by RheaAyase** [comment] 2020-10-02 10:38
Please close this?

**Comment by SubZero0** [comment] 2020-11-07 03:07
I'll be closing this since a lot of changes were made since it was created.
If you have any issue like this one, I recommend updating to the latest nightly and if not resolved, create a new issue or check #960

**Closed as completed by SubZero0** 2020-11-07 03:07 UTC
